name: Publish extension

on: push

jobs:
  package-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
      - uses: actions/checkout@v3
      - name: Install VSCode Extension Manager
        run: npm install --global @vscode/vsce
      - name: Install dependencies
        run: npm i
      - name: Create .vsix package
        run: vsce package
      - name: Publish artifact
        uses: actions/upload-artifact@v3
        with:
          name: vscode-extension
          path: *.vsix
